MODE: IDN

TRAIN:
  DATA_DIR: data_vcl
  DATASET:
    NUM_NEG: 8
    BATCH_SIZE: 15
    NUM_WORKERS: 3
    SAMPLER_NAME: "priority_object"
    JITTERING: True
    IPT: True
  MAX_EPOCH: 30
  OPTIMIZER:
    TYPE: SGD
    lr: 
        1e-3
    momentum: 0.9
    weight_decay: 1e-7
    alpha: 0.99
    eps: 1e-8
  
TEST:
  NIS: True
  BATCH_SIZE: 135
  NUM_WORKERS: 3

MODEL:
  AE:
    BIN: True
    BIN_LOSS_MODE: 2
    BIN_FAC: 0.2
    CHECKPOINT: 
    BN: True
    DROPOUT:
    SPATIAL:
      LAYER_SIZE: [8, 256, 512]
    ENCODER:
      LAYER_SIZE: [4608, 4096, 1024]
    LOSS:
      RECONSTRUCTION_FAC: 0.4
      CLASSIFICATION_FAC: 1.0
    NUM_CLASSES: 117
  IDN:
    CHECKPOINT: 
        'exp/IDN_IPT_hico/epoch_30.pth'
    NAME: 'Transformer'
    PROJ: False
    REVERSE: True
    REVERSE_FAC: 0.5
    LAYER_SIZE: [1024, 512, 1024]
    NUM_CLASSES: 117
    CLASSIFICATION_FAC: 1.0
    AUTOENCODER_FAC: 0.1
    BINARY: True
    BINARY_FAC: 0.2
